# Generated by Django 5.0.14 on 2025-08-17 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_studyspot_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyspot',
            name='image_url',
        ),
        migrations.CreateModel(
            name='SpotImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(default='pikachu.jpg', max_length=100)),
                ('studySpot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.studyspot')),
            ],
        ),
    ]
